### PR TITLE
add GTM to default web html

### PR DESCRIPTION
**Pull request by Nkdiaz**
as part of improving general google analytics, I am adding tags to the email body and the website to track user metrics for the gtfs quality reports

### CODE REVIEW

**Review by evansiroky — COMMENTED** [review]
Ideally, the Google Analytics and Google Tag keys should be read from a secret config file and not checked into the repo.

**Comment by thekaveman** [comment]
> Ideally, the Google Analytics and Google Tag keys should be read from a secret config file and not checked into the repo.

From a maintenance point of view this could make it easier, to only have one place to update the value and share across usages. From the point of view of "best practices to keep secrets out of the repo" -- remember these aren't _really_ secrets, they have to be sent to the browser in order to do anything, by definition they are public. 

We commit the GA IDs directly to files in the repo in many other cases: for [MobiMart](https://github.com/cal-itp/mobility-marketplace/blob/main/_config.yml#L27), [calitp.org](https://github.com/cal-itp/website/blob/main/_config.yml#L8), all the [docs sites](https://github.com/cal-itp/mkdocs-template/blob/main/mkdocs.yml#L29), etc.

**Comment by themightychris** [comment]
> to only have one place to update the value and share across usages

That's the whole value prop of using GTM in the middle...we can just hardcode the GTM block everywhere and then control what's deployed from the GTM console

**Review by themightychris — CHANGES_REQUESTED** [review]
@Nkdiaz actually, one change we should make before merging is to remove the changes to the email template. Tracking codes aren't going to work in email bodies pretty much anywhere, so let's remove it entirely to avoid the risk that they cause issues anywhere

**Review by Nkdiaz — COMMENTED** [review]
makes sense

**Review by themightychris — APPROVED** [review]
@thekaveman does this GTM account have the right ownership set up?

**Comment by thekaveman** [comment]
Sorry @themightychris not sure what you mean by the "right ownership"? 

Compiler has the GA property, @Nkdiaz was given admin permissions and did the configuration for GTM.

**Comment by themightychris** [comment]
@thekaveman I find this all very confusing personally because it seems like GTM/GA call multiple things accounts, and I struggle with figuring out how to move things around in the hierarchy. AFAICT there are:

- organization accounts
- analytics accounts
- tag manager accounts

Analytics and tag manager accounts can both be "under" an organization. A GTM account can't be "under" a GA account though. What I'm looking to confirm is that the GTM account we're using has made its way under whatever organization account we're using. Like how here the "Code for Philly" GTM account is under the "Code for Philly" organization account:

Screen Shot 2022-03-18 at 4 53 26 PM

**Comment by thekaveman** [comment]
@themightychris yes I agree, it is confusing. I'm with you now - I was under the mistaken impression that a GTM account was "under" a GA account. 

What you describe is partially how it is set up for the Cal-ITP on the GA side:

image

And I started to do the same thing on the GTM side:

image

I see what you mean by the "organization" account though now - we don't currently have one for Cal-ITP but I'll get that setup and migrate these GA/GTM accounts in.

**Comment by thekaveman** [comment]
OK, done:

image

image

**Review by blakeflei — APPROVED** [review]

**Pull request merged**
