### PR TITLE
Issue 183/rt presence and speedmap

### LINKED ISSUE #183: User Story: Reports include RT presence and speedmap link, if available
### Summary

As a transit agency or other interested stakeholder, I want to know if my agency currently publishes a GTFS-RT feed so that I know whether or not we are providing realtime information to riders. Additionally, I want to be able to see my [speedmap](https://analysis.calitp.org/rt/README.html) if available so that I can work with Caltrans and other jurisdictions to advance transit priority projects. 

### Acceptance Criteria

1. [report](https://reports.calitp.org/gtfs_schedule/2022/07/300/index.html) indicates presence of GTFS-RT feed
1. [report](https://reports.calitp.org/gtfs_schedule/2022/07/300/index.html) includes link to [relevant speedmap](https://analysis.calitp.org/rt/district_07-los-angeles/5__speedmaps__district_07-los-angeles__itp_id_300.html), if any 
2. report includes brief text explaining relevance of GTFS-RT and requirements to generate a speedmap

### Notes

Ideally this could be implemented soon, before GTFS-RT mart tables are fully built out. One approach could be to generate the links from https://github.com/cal-itp/data-analyses/blob/main/portfolio/sites/rt.yml 

### Tester [Stakeholder]

1. @edasmalchi 

# Sprint Ready Checklist
1. - [ ] Acceptance criteria defined
3. - [ ] Team understands acceptance criteria
4. - [ ] Team has defined solution / steps to satisfy acceptance criteria
5. - [ ] Acceptance criteria is verifiable / testable
6. - [ ] External / 3rd Party dependencies identified

### PR DESCRIPTION
**Pull request by chriscauley**
# Description

This is incomplete right now. It adds a check mark if the route has an RT Feed and speedmap link if one exists. However it needs a designer to approve the changes (I just sort of stuck things in a spot that made sense to me) and doesn't satisfy the issue requirement below. I don't have the domain knowledge to add this copy.

* MISSING REQUIREMENT: report includes brief text explaining relevance of GTFS-RT and requirements to generate a speedmap

Resolves #183

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

## Screenshots (optional)

Here's a screenshot of a feed that DOES NOT have an RT Feed or a speedmap link (this is the status quo)
image

Here's a screenshot of a feed that DOES have an RT feed and a speedmap link. I need the copy mentioned above to finish this.

image

### CODE REVIEW

**Comment by acouch** [comment]
I've tested this locally. Looks good. Will get feedback on the design or description.

**Comment by acouch** [comment]
Some feedback:

* Some Agencies have an RT Feed, but no feed map. We should use https://github.com/cal-itp/data-infra/blob/main/airflow/data/agencies.yml to determine if there is an RT feed. We will need to include the RT Feed check-mark for those agencies. Caltran, id 246, is an example.
* We expect to get design feedback next week.

**Comment by chriscauley** [comment]
I made the above changes. Here are some questions I ran into.

* Previously I was using https://raw.githubusercontent.com/cal-itp/data-analyses/main/portfolio/sites/rt.yml to get the RT feeds. Now I'm using both that and the rt feed (see @acouch's comment above)
* The first screenshot shows a report without gtfs rt info
* The second screenshot shows a report with gtfs rt info

image

image

**Review by acouch — APPROVED** [review]
I've tested this locally and made one update.

**Review by edasmalchi — APPROVED** [review]
lgtm, excited for this!

**Pull request merged**
